tabWidth: 4
singleQuote: true
printWidth: 120
useTabs: false
semi: false
trailingComma: 'all'
bracketSpacing: true
bracketSameLine: true
arrowParens: 'avoid'

plugins:
  - prettier-plugin-apex
  - '@prettier/plugin-xml'

overrides:
  - files: ['*.cls', '*.trigger']
    options:
      parser: apex
      apexInsertFinalNewline: true
  - files: ['*.xml']
    options:
      parser: xml
      xmlSelfClosingSpace: false
      printWidth: 1000
  - files: '**/lwc/**/*.html'
    options:
      parser: 'lwc'
  - files: '*.{cmp,page,component}'
    options:
      parser: 'html'
  - files: ['*.yml', '*.yaml']
    options:
      tabWidth: 2
